name: Merge Minifications

on:
  workflow_run:
    workflows: ["JSON Validation and Minification", "XML Validation and Minification"]
    types:
      - completed

jobs:
  merge-minifications:
    runs-on: ubuntu-latest
    needs: [check-json, check-xml] # Ensure both workflows completed

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Merge JSON Changes
        run: |
          git fetch origin json-minification
          git checkout -b merged-changes
          git merge json-minification --no-ff --no-commit

      - name: Merge XML Changes
        run: |
          git fetch origin xml-minification
          git merge xml-minification --no-ff --no-commit

      - name: Push merged changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Sudachi"
          git config user.email "sudachi@cirno.name"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
          git push origin --delete json-minification-${{ github.event.pull_request.number }} || echo "No XML temporary branch to delete."
          git push origin --delete xml-minification-${{ github.event.pull_request.number }} || echo "No XML temporary branch to delete."
