name: XML Validation and Minification

on:
  pull_request:
    paths:
      - 'magica/**/*.plist'
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  check-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      - name: Get Changed XML Files
        id: changed_files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/base
          CHANGED_XML_FILES=$(git diff --name-only origin/base...${{ github.sha }} | grep '\.plist$' | tr '\n' ' ')
          echo "files=$CHANGED_XML_FILES" >> $GITHUB_OUTPUT

      - name: Validate XML Files
        id: validate_xml
        run: |
          invalid_files=""
          for file in ${{ steps.changed_files.outputs.files }}; do
            if ! xmllint --noout "$file" 2>/dev/null; then
              NEWLINE=$'\n'
              invalid_files="$invalid_files$NEWLINE$file"
            fi
          done

          if [ -n "$invalid_files" ]; then
            {
              echo 'INVALID_FILES<<EOF'
              echo "$invalid_files"
              echo EOF
            } >> "$GITHUB_ENV"
            exit 1
          fi

      - name: Post comment on PR if invalid XML found
        if: failure()
        uses: actions/github-script@v7
        env:
          INVALID_FILES: ${{ env.INVALID_FILES }}
        with:
          script: |
            const invalidFiles = process.env.INVALID_FILES;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The following XML files are invalid:\n\`\`\`${invalidFiles}\n\`\`\``
            });

      - name: Minify XML Files
        run: |
          for file in ${{ steps.changed_files.outputs.files }}; do
            minified=$(xmllint --noblanks --format "$file")
            echo "$minified" > "$file"
          done

      - name: Commit and rebase if files were minified
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "Sudachi"
            git config user.email "sudachi@cirno.name"
            git commit -am "minify XML files"
            git fetch origin ${{ github.event.pull_request.base.ref }}
            git rebase origin/${{ github.event.pull_request.base.ref }}
            git push --force origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            echo "No changes to commit."
          fi
